{% set name = "znh5md" %}
{% set version = "0.4.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/znh5md-{{ version }}.tar.gz
  sha256: aeb7ae5f25e2a52e1e265e0d761e1cd6224cb92d574984e62fccf0ef2fb1c03c

build:
  entry_points:
    - znh5md = znh5md.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - plams >=2025.102
    - python >={{ python_min }},<4.0.0
    - h5py >=3.12.1
    - ase >=3.24.0
    - tqdm >=4.67.1
    - typer >=0.15.1

test:
  imports:
    - znh5md
  commands:
    - pip check
    - znh5md --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zincware/ZnH5MD
  summary: ASE Interface for the H5MD format.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
